MarketKurly/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_list, name='cart_list'),
    path('add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('update_quantity/<int:item_id>/', views.update_quantity, name='update_quantity'),
    path('delete_selected/', views.delete_selected, name='delete_selected'),
]

MarketKurly/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path('product/', include("product.urls")),
    path('cart/', include('cart.urls')),
    path('wishlist/', include('wishlist.urls')),
    path('users/', include("users.urls")),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

MarketKurly/product/urls.py
from django.urls import path
from .views import ProductLV, ProductDV, NewProductLV, MainCategoryLV, SubCategoryLV, SearchProductLV

app_name = 'product'

urlpatterns = [
    path('', ProductLV.as_view(), name='index'),
    path('detail/<int:pk>/', ProductDV.as_view(), name='product_detail'),
    path('new/', NewProductLV.as_view(), name='new_product'),
    path('category/<int:category_id>/', MainCategoryLV.as_view(), name='main_category'),
    path('subcategory/<int:subcategory_id>/', SubCategoryLV.as_view(), name='sub_category'),
    path('search/', SearchProductLV.as_view(), name='search_products'),
] 

MarketKurly/wishlist/urls.py
from django.urls import path
from . import views

app_name = 'wishlist'

urlpatterns = [
    path('', views.wishlist_list, name='wishlist_list'),
    path('add/<int:product_id>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('remove/<int:item_id>/', views.remove_from_wishlist, name='remove'),
]

MarketKurly/product/models.py
from django.db import models
from django.urls import reverse
from .fields import ThumbImageField

class Category(models.Model):
    name = models.CharField('Category name', max_length=255)
    parent_category = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True, related_name='subcategory') 

    def __str__(self):
        name_parts = [
            'sub:' + self.name if self.parent_category else self.name,
            'main:' + self.parent_category.name if self.parent_category else ''
        ]
        result = (
            " > ".join(
                map(
                    str.strip, 
                    [name_parts[0], name_parts[1]]
                )
            ) if self.parent_category else "{}".format(self.name)
        )
        return result if result and len(result) > 0 else "No Name"


class Products(models.Model):
    image = ThumbImageField(upload_to='product/%Y/%m')
    name = models.CharField('Product name', max_length=255, blank=False, null=False)
    description = models.TextField('Product Description', blank=True)
    price = models.PositiveIntegerField()
    stock = models.PositiveIntegerField()
    create_dt = models.DateField(auto_now_add=True)
    update_dt = models.DateField(auto_now=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    owner = models.CharField(max_length=100, default='Kurly')

    class Meta:
        ordering = ('name',)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('product:product_detail', args=(self.id,))

MarketKurly/product/views.py
from collections.abc import Sequence
from typing import Any
from django.db.models.query import QuerySet
from django.views.generic import ListView, DetailView
from .models import Products, Category
from django.db.models import Q

# Create your views here.
class ProductLV(ListView):
    model = Products
    context_object_name = "product_list"

class ProductDV(DetailView):
    model = Products

class NewProductLV(ListView):
    model = Products
    template_name = 'product/new_list.html'
    ordering = ('-create_dt')

    paginate_by= 6

class MainCategoryLV(ListView):
    model = Products
    template_name = 'product/main_category_list.html'

    def get_queryset(self):
        category_id = self.kwargs.get('category_id')
        subcategories = Category.objects.filter(parent_category_id=category_id)
        return Products.objects.filter(category__in=subcategories)
    
    def get_context_data(self, **kwargs: Any):
        context = super().get_context_data(**kwargs)
        category_id = self.kwargs.get('category_id')
        category = Category.objects.get(id=category_id)
        context['category'] = category
        context['subcategory'] = category.subcategory.all()
        return context
        

class SubCategoryLV(ListView):
    model = Products
    template_name = 'product/sub_category_list.html'
    paginate_by = 3

    def get_queryset(self) -> QuerySet[Any]:
        subcategory_id = self.kwargs.get('subcategory_id')
        return Products.objects.filter(category_id=subcategory_id)

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        subcategory_id = self.kwargs.get('subcategory_id')
        subcategory = Category.objects.get(id=subcategory_id)
        
        context['subcategory'] = subcategory
        return context



class SearchProductLV(ListView):
    model = Products
    template_name = 'product/search_results.html'
    context_object_name = 'product_list'

    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            return Products.objects.filter(
                Q(name__icontains=query) | Q(description__icontains=query)
            )
        else:
            return Products.objects.all()

MarketKurly/product/templates/product/main_category_list.html
{% extends 'base.html' %}

{% block title %}Main Category List{% endblock %}

{% block content %}
<h1 class="text-center">{{ category.name }}의 제품들</h1>

<div class="container mt-4">
    <div class="row">
        {% for sub in subcategory %}
            <div class="col-3 mb-3 text-center">
            <a href="{% url 'product:sub_category' sub.id %}" style="color:purple">{{ sub.name }}</a>
            </div>
        {% empty %}
            <h3 class="text-center">상품을 준비중입니다...</h3>
        {% endfor %}
    </div>
</div>
<hr></hr>
<div class="container text-center">
    <div class="row">
    {% for object in object_list %}
    <div class="col-4 mb-2">
        <div class="thumbnail">
            <a href="{{ object.get_absolute_url }}">
                <img src="{{ object.image.thumb_url }}" style="width: 180px; height: 225px; object-fit: cover;">
                <p class="mt-2">{{ object.name }}</p>
            </a>
            <p>{{ object.price }}원</p>
        </div>
    </div>
    {% endfor %}
    </div>
</div>
{% endblock %}

MarketKurly/product/templates/product/new_list.html
{% extends 'base.html' %}

{% block title %}New Product{% endblock %}

{% block content %}
<div class="container text-center">
    <div class="row">
    {% for object in object_list %}
    <div class="col mx-3">
        <div class="thumbnail">
            <a href="{{ object.get_absolute_url }}">
                <img src="{{ object.image.thumb_url }}" style="width: 180px; height: 225px; object-fit: cover;">
                <p class="mt-2">{{ object.name }}</p>
            </a>
            <p>{{ object.price }}원</p>
        </div>
    </div>
    {% endfor %}
    </div>
</div>
{% endblock %}

{% block footer %}
<div class="container text-center">
    <div style="padding-bottom: 20px;"></div>
        <span>
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number}}"><i class="fa-solid fa-arrow-left"></i></a>
            {% endif %}
            Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}
            {% if page_obj.has_next %}
                <a href="?page={{page_obj.next_page_number}}"><i class="fa-solid fa-arrow-right"></i></a>
            {% endif %}
        </span>
    </div>
</div>
{% endblock %}

MarketKurly/product/templates/product/products_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}product detail{% endblock %}

{% block extra-style %}
<style type="text/css">
.custom-btn {
    background-color: purple;
    color: white;
    border: none;
    padding: 10px 20px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    cursor: pointer;
}

.custom-btn:hover {
    background-color: darkviolet;
}
</style>
{% endblock %}

{% block content %}
<h2 class="mt-5" style="color:#09ff00">{{ object.title }}</h2>

<div class="row">
    <div class="col-md-6">
        <a href="{{object.image.url}}">
            <img src="{{object.image.url}}" style="width: 100%;">
        </a>
    </div>

    <ul class="col-md-6 mt-3">
        <p class="h4">{{object.name}}</p>
        <p class="h2 fw-bold">{{object.price}}원&ensp;({{object.stock}}개&ensp;남음)</p> 
        <p>판매자&emsp;{{object.owner}}</p>
        <p>{{ object.description }}</p>
        <div class="container-fluid">
            <a class="btn btn-outline-secondary" href="{% url 'wishlist:add_to_wishlist' object.id %}" role="button"><i class="fa-regular fa-heart" style="color: #B197FC;"></i></a>&emsp;
            <a class="btn custom-btn" href="{% url 'cart:add_to_cart' object.id %}" role="button">장바구니 담기</a>
        </div>
    </ul>
</div>
{% endblock %}

MarketKurly/product/templates/product/products_list.html
{% extends 'base.html' %}

{% block title %}Market Kurly{% endblock %}

{% block content %}
    <div class="container text-center">
        <div class="row">
        {% for product in product_list %}
        <div class="col-4 mb-2">
            <div class="thumbnail">
                <a href="{{ product.get_absolute_url }}">
                    <img src="{{ product.image.thumb_url }}" style="width: 180px; height: 225px; object-fit: cover;">
                    <p class="mt-2">{{ product.name }}</p>
                </a>
                <p>{{ product.price }}원</p>
            </div>
        </div>
        {% endfor %}
        </div>
    </div>
{% endblock %}

MarketKurly/product/templates/product/search_result.html
{% extends 'base.html' %} 

{% load static %}

{% block title %}검색 결과{% endblock %} 

{% block content %}

<div class="container text-center">
    <h1>검색 결과</h1>

    {% if products %}
    <div class="row">
        {% for product in product_list %} 
        <div class="col-4 mb-2">
            <div class="thumbnail">
                <a href="{{ product.get_absolute_url }}">
                    <img src="{{ product.image.thumb_url }}" style="width: 180px; height: 225px; object-fit: cover;">
                    <p class="mt-2">{{ product.name }}</p>
                </a>
                <p>{{ product.price }}원</p>
            </div>
        </div>
        {% endfor %}
    </div>
    {% else %}
    <p>검색 결과가 없습니다.</p>
    {% endif %}
</div>

{% endblock %}

MarketKurly/product/templates/product/sub_category_list.html
{% extends 'base.html' %}

{% block title %}Sub Category List{% endblock %}

{% block content %}
<h1 class="text-center">{{ subcategory.name }} 상품들</h1>
<hr></hr>
<div class="container text-center">
    <div class="row">
    {% for object in object_list %}
    <div class="col mx-3">
        <div class="thumbnail">
            <a href="{{ object.get_absolute_url }}">
                <img src="{{ object.image.thumb_url }}" style="width: 180px; height: 225px; object-fit: cover;">
                <p class="mt-2">{{ object.name }}</p>
            </a>
            <p>{{ object.price }}원</p>
        </div>
    </div>
    {% empty %}
    <h3 class="text-center">상품을 준비중입니다...</h3>
    {% endfor %}
    </div>
</div>
{% endblock %}

{% block footer %}
<div class="container text-center">
    <div style="padding-bottom: 20px;"></div>
        <span>
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number}}"><i class="fa-solid fa-arrow-left"></i></a>
            {% endif %}
            Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}
            {% if page_obj.has_next %}
                <a href="?page={{page_obj.next_page_number}}"><i class="fa-solid fa-arrow-right"></i></a>
            {% endif %}
        </span>
    </div>
</div>
{% endblock %}