MarketKurly/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_list, name='cart_list'),
    path('add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('update_quantity/<int:item_id>/', views.update_quantity, name='update_quantity'),
    path('delete_selected/', views.delete_selected, name='delete_selected'),
]

MarketKurly/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path('product/', include("product.urls")),
    path('cart/', include('cart.urls')),
    path('wishlist/', include('wishlist.urls')),
    path('users/', include("users.urls")),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

MarketKurly/product/urls.py
from django.urls import path
from .views import ProductLV, ProductDV, NewProductLV, MainCategoryLV, SubCategoryLV, SearchProductLV

app_name = 'product'

urlpatterns = [
    path('', ProductLV.as_view(), name='index'),
    path('detail/<int:pk>/', ProductDV.as_view(), name='product_detail'),
    path('new/', NewProductLV.as_view(), name='new_product'),
    path('category/<int:category_id>/', MainCategoryLV.as_view(), name='main_category'),
    path('subcategory/<int:subcategory_id>/', SubCategoryLV.as_view(), name='sub_category'),
    path('search/', SearchProductLV.as_view(), name='search_products'),
] 

MarketKurly/users/urls.py
from django.urls import path
from users import views

app_name = "users"

urlpatterns = [
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("signup", views.signup_view, name="signup"),
    path("usersinfo", views.usersinfo_view, name="usersinfo"),
    
]

MarketKurly/wishlist/urls.py
from django.urls import path
from . import views

app_name = 'wishlist'

urlpatterns = [
    path('', views.wishlist_list, name='wishlist_list'),
    path('add/<int:product_id>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('remove/<int:item_id>/', views.remove_from_wishlist, name='remove'),
]

MarketKurly/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Kurly{% endblock %}</title>
    <!-- Bootstrap CSS link -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/style2.css' %}">

    {% block extra-style %}{% endblock %}
</head>
<body>
    <!-- Fixed Navigation Bar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'product:index' %}">
                <img src="{% static 'img/kurly-logo.svg' %}" alt="Kurly Logo">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="dropdown" aria-expanded="false">>
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <!-- Category Dropdown -->
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <img src="{% static 'img/hamburger.svg' %}" alt="Kurly Logo">
                        </a>
                        <ul class="dropdown-menu">
                            {% for category in categories %}
                            {% if category.subcategory.exists %}
                            <li class="dropdown-submenu">
                                <a class="dropdown-item" href="{% url 'product:main_category' category.id %}">{{ category.name }}</a>
                                {% if category.subcategory.exists %}
                                <ul class="dropdown-menu">
                                    {% for subcategory in category.subcategory.all %}
                                    <li><a class="dropdown-item" href="{% url 'product:sub_category' subcategory.id %}">{{ subcategory.name }}</a></li>
                                    {% endfor %}
                                </ul>
                                {% endif %}
                            </li>
                            {% endif %}
                            {% endfor %}
                        </ul>
                    </li>
                </ul>
                
                
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'product:new_product' %}">신상품</a>
                    </li>
                </ul>

                <!-- Search Form -->
                <form class="d-flex mx-auto navbar-search">
                    <input class="form-control me-2" type="search" placeholder="검색어를 입력해주세요" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">
                        <img src="{% static 'img/search.svg' %}" style="width: 25px; height: 25px;">
                    </button>
                </form>

                <!-- Right-side Links (Wishlist, Cart, Login/Logout) -->
                <ul class="navbar-nav ms-auto">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">로그아웃</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:signup' %}">회원가입</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">로그인</a>
                    </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'wishlist:wishlist_list' %}">
                            <!--장고 템플릿 정식 작업 때 사용-->
                            <!-- <img src="{% static 'img/heart-icon.png' %}" alt="Wishlist" style="height: 20px;"> -->
                            <img src="{% static 'img/wish.svg' %}" style="width: 30px;">
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'cart:cart_list' %}">
                            <!--장고 템플릿 정식 작업 때 사용-->
                            <!-- <img src="{% static 'img/cart-icon.png' %}" alt="Cart" style="height: 20px;"> -->
                            <img src="{% static 'img/cart.svg' %}" style="width: 30px;">
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <!-- Main content of each page will be inserted here -->
    <main class="container" style="margin-top: 80px;">
        {% block content %}
        {% endblock %}
    </main>

    <!-- Bootstrap JS and Popper.js -->
     {% block footer %}{% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>
    <script src="https://kit.fontawesome.com/b572e80bf8.js" crossorigin="anonymous"></script>

    {% block extra-script %}{% endblock %}
</body>
</html>