MarketKurly/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_list, name='cart_list'),
    path('add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('update_quantity/<int:item_id>/', views.update_quantity, name='update_quantity'),
    path('delete_selected/', views.delete_selected, name='delete_selected'),
]

MarketKurly/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path('product/', include("product.urls")),
    path('cart/', include('cart.urls')),
    path('wishlist/', include('wishlist.urls')),
    path('users/', include("users.urls")),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

MarketKurly/product/urls.py
from django.urls import path
from .views import ProductLV, ProductDV, NewProductLV, MainCategoryLV, SubCategoryLV, SearchProductLV

app_name = 'product'

urlpatterns = [
    path('', ProductLV.as_view(), name='index'),
    path('detail/<int:pk>/', ProductDV.as_view(), name='product_detail'),
    path('new/', NewProductLV.as_view(), name='new_product'),
    path('category/<int:category_id>/', MainCategoryLV.as_view(), name='main_category'),
    path('subcategory/<int:subcategory_id>/', SubCategoryLV.as_view(), name='sub_category'),
    path('search/', SearchProductLV.as_view(), name='search_products'),
] 

MarketKurly/users/urls.py
from django.urls import path
from users import views

app_name = "users"

urlpatterns = [
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("signup", views.signup_view, name="signup"),
    path("usersinfo", views.usersinfo_view, name="usersinfo"),
    
]

MarketKurly/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class User(AbstractUser):
    GENDER_CHOICES = [
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other'),
    ]
    user_id = models.CharField(max_length=10)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES,  default='O')
    birth = models.DateField(blank=True, null=True)
    profile_image = models.ImageField(upload_to='profile_images/', null=True, blank=True)
    short_description = models.CharField(max_length=500, null=True, blank=True)

MarketKurly/users/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect
from users.models import User
import datetime
from django.contrib import messages
# Create your views here.

def login_view(request):
    if request.method == "POST":
        print(request.POST)
        username = request.POST.get("username", "")
        email = request.POST.get("email", "")
        password = request.POST.get("password", "")
    #    username = request.POST["username"]
    #    email = request.POST["email"]
    #    password = request.POST["password"]
        user = authenticate(username=username, email=email, password=password)
        print(user)
    #    print(email)
        if user is not None:
            print("인증성공")
            login(request, user)
        else:
            print("인증실패")
            messages.error(request, "로그인에 실패했습니다. 다시 시도하세요.")    

    return render(request, "users/login.html")



def logout_view(request):
    logout(request)
    messages.success(request, "성공적으로 로그아웃을 했습니다!!")
    return render(request, "users/logout.html")

def signup_view(request):
    if request.method == "POST":
        print(request.POST)
        username = request.POST.get("username", "")
    #    username = request.POST["username"]
        password = request.POST["password"]
        email = request.POST["email"]
        firstname = request.POST["firstname"]
        lastname = request.POST["lastname"]
        gender = request.POST["gender"]
        birth = request.POST["birth"]
        profile_image = request.FILES.get('profile_image')
        short_description = request.POST['short_description']

        try:
            birth = datetime.datetime.strptime(birth, "%Y-%m-%d").date()
        except ValueError:
        # 날짜 형식이 맞지 않을 때 처리
            return render(request, "users/signup.html", {"error": "Invalid birth date format."})
        
        users = User.objects.create_user(username,  email, password,)
        print(users)
        users.last_name = lastname
        users.first_name = firstname
        users.gender = gender
        users.birth = birth
        users.profile_image = profile_image
        
        users.short_description = short_description
        print(users)
        users.save()
        return redirect("users:login")
    return render(request, "users/signup.html")


def usersinfo_view(request):
    if request.method == "POST":
        print(request.POST)
    return render(request, "users/usersinfo.html")

MarketKurly/users/templates/users/login.html
<div class="wrapper">
 <div class="container">
       
    {% if user.is_authenticated %}
        로그인 성공
        <br>
        {{ user.email }}님 환영합니다!
        <br>
        <a href="{% url 'users:usersinfo' %}">회원정보페이지</a>로 이동합니다.
        <br>
        <br>
        
        <a href="{% url 'users:logout' %}">로그아웃</a>
    {% else %}
        
    

    <h2>로그인</h2>  
 <div class="child">  
    <form action="" method="POST">
        {% csrf_token %}
        <label for="username">아이디:</label>
        <input tyepe="username" name="username">
        <br>
        <label for="email">이메일:</label>
        <input type="email" id="email" name="email">
        <br>
        <label for="password">비밀번호:</label>
        <input name="password" type="password">
  </div>   
        <input class="login_button" type="submit" value="로그인">
        <br>
        <a style="font-size: 15px;" href="{% url 'users:signup' %}">회원가입</a>
    </form>
{% endif %}
 </div>
</div>
<style>

    .wrapper {
        margin-top: 300px;
        display: flex;
        justify-content: center;
        align-items: center; 
    }
    .container {   
        font-family: arial;
        font-size: 24px;
        margin: 1px;
        width: 410px;
        height: 320px;
        outline: dashed 1px rgb(91, 89, 89);
        text-align: center;
        padding-right: 20px;
    }
    .child {
        font-family: arial;
        font-size: 20px;
        margin: 25px;
        width: 300px;
        height: 100px;
        text-align: right;
    }
    .login_button {
        background-color: #5F0080;
        color: white;   
    }
</style>


MarketKurly/users/templates/users/logout.html
<div class="wrapper">
    <div class="container">      
        로그아웃 성공했습니다!
        <br>   
        <a href="{% url 'product:index' %}">홈</a>    
    </div>
</div>
   <style>
   
       .wrapper {
           margin-top: 300px;
           display: flex;
           justify-content: center;
           align-items: center; 
       }
       .container {   
           font-family: arial;
           font-size: 24px;
           margin: 1px;
           width: 410px;
           height: 320px;
           outline: dashed 1px rgb(91, 89, 89);
           text-align: center;
           padding-right: 20px;
       }
       .child {
           font-family: arial;
           font-size: 20px;
           margin: 25px;
           width: 300px;
           height: 100px;
           text-align: right;
       }
       .login_button {
           background-color: #5F0080;
           color: white;   
       }
   </style>
   

MarketKurly/users/templates/users/signup.html

<div class="signup_wrapper">
    <div class="signup_container"> 
        <h2>회원가입</h2>
        <form action="" method="POST">
            {% csrf_token %}  <!--form  요청시.. -->
        <div class="signup_child"> 
            <label for="username">아이디:</label>
            <input name="username" type="text">  
            <br>
            <label for="password">비밀번호:</label>
            <input name="password" type="password">
            <br>
            <label for="email">이메일:</label>
            <input name="email" type="text">
            <br>
            <label for="firstname">이름:</label>
            <input name="firstname" type="text">
            <br>
            <label for="lastname">성:</label>
            <input name="lastname" type="text">
            <br>  
            <label>성별:</label>
            <label>
            <input type="radio" name="gender" value="남성">남성
            </label>
            <label>
            <input type="radio" name="gender" value="여성">여성
            </label>
            <label>
                <input type="radio" name="gender" value="여성">기타
            </label>
            <br>
        </div> 
            <br>
            <br>   
            <label style="font-size: 15px;" for="date">생년월일:</label>
            <input type="date" max="9999-12-31" name="birth">
            <br>
            <br>
            
            <label style="align-self:left;  " for="profile_image" class="form-label">프로필이미지선택하세요.</label>
            <input class="form-control form-control-lg" id="profile_image" type="file">
            <br>
            <br>
            <label style="font-size: 15px;" for="short_description">비고:</label>
            <input name="short_description" type="text">
            <br>
            
            <br>
            
           
            <input class="signup_button" type="submit" value="회원가입완료">
            <br>
            <a style="font-size: 15px;" href="{% url 'users:usersinfo' %}">로그인</a>
            
        </form>
    </div>
</div>
<style>
    .signup_wrapper {
        margin-top: 300px;
        display: flex;
        justify-content: center;
        align-items: center; 
    }
    .signup_container {
        font-family: arial;
        font-size: 24px;
        margin: 1px;
        width: 350px;
        height: 550px;
        outline: dashed 1px rgb(91, 89, 89);
        text-align: center;
        padding-right: 20px;  
    }

    .signup_child {
       
        font-family: arial;
        font-size: 20px;
        margin: 25px;
        width: 300px;
        height: 100px;
        text-align: right;
    
    }

    .signup_button {
        background-color: #5F0080;
        color: white;   
    }
</style>

MarketKurly/users/templates/users/usersinfo.html

<div class="usersinfo_wrapper">
    <div class="usersinfo_container">

    회원정보페이지
    <br>
    <br>
    {{ user.username }}님 정보 페이지
    <br>
    email:{{ user.email}}
    <br>
    성명:
    {{ user.last_name }}
    {{ user.first_name }}
    <br>
    성별:{{ user.gender }}  (예:['O':기타] )    
    <br>
    생년월일:{{ user.birth }}
    <br>

    <a href="{% url 'users:logout' %}">로그아웃</a>

    </div>
</div>

<style>

    .usersinfo_wrapper {
        margin-top: 300px;
        display: flex;
        justify-content: center;
        align-items: center; 
    }
    .usersinfo_container {   
        font-family: arial;
        font-size: 24px;
        margin: 1px;
        width: 400px;
        height: 320px;
        outline: dashed 1px rgb(91, 89, 89);
        text-align: center;
        padding-right: 20px;
    }